### ISSUE TITLE
Nothing changes when you run BAT. The CMD window briefly turns on and off.

### ISSUE THREAD

**Issue by Zeratus13** [BytePhoenixData/BSCTokenSniper#1]
Nothing changes when you run BAT.
The CMD window briefly turns on and off.

**Comment by Byte-Phoenix** [comment]
Check:

Python 3+ installed?

web3 installed correctly?
 (you could create extra python script with 'from web3 import Web3', if running in IDLE gives you an error then web3 isn't installed correctly)

config file configured correctly (no syntax errors, extra commas etc)?

**Comment by rickyrvp** [comment]
Same problem.. everything installed, no text except the run command

**Comment by git-me-a-cold-POP** [comment]
I am having the same issue as above. Could you offer some more possible solutions? Thanks.

**Comment by nandofmike** [comment]
Around here the same problem

**Comment by CnKore-zzb** [comment]
Most of them are because your Web3 installation failed

**Comment by CnKore-zzb** [comment]
Forget to say the solution, please do not install Web3 under NPM, you can enter “pip install Web3” in the CMD

Let Python call Web3 module is the same effect

**Comment by BytePhoenixData** [comment]
Most likely either python version is too old or web3 isnt correctly installed. Im still working on a fix for the web3 issue

**Comment by BytePhoenixData** [comment]
I have just installed python on my laptop (windows 8) and got it successfully to work. I installed python 3.9.6 and installed web3 using 'npm install web3' but that didn't work.

Fix that worked for me:
Try 'py -m pip install web3' or replace 'py' with python if you have a python older version. 

Worked right away after that. Let me know if that works.

**Comment by geeks121** [comment]
you can run with python3 directly
