### ISSUE TITLE
ctypes windll fails on mac and linux

### ISSUE THREAD

**Issue by shaiss** [BytePhoenixData/BSCTokenSniper#12]
https://github.com/BytePhoenixData/BSCTokenSniper/blob/69c7d0d6ac9630da72c59e412fce536f96827ff6/BSCTokenSniper.py#L40

ctypes.windll.kernel32.SetConsoleTitleW("BSCTokenSniper | Loading...")

There's an error on mac and linux with this line and 103 that references windll.

Looking at the docs, I can't figure out the equivalent on mac/*nix so I commented those lines out.

https://docs.python.org/3/library/ctypes.html

Any suggestions how to fix this?

**Comment by geeks121** [comment]
you can go to my fork

select linux branch : 

[https://github.com/geeks121/BSCTokenSniper](url)

**Comment by phoenix-blue** [comment]
used your script but because I have installes python3 I must start it with python3 run.py

After using option 3 I get the next error:

Please the menu :  3
Installing Dependency
sh: 1: python: not found
sh: 1: python: not found

How can I solve this problem?

**Comment by BytePhoenixData** [comment]
I also have a mac so will adjust for mac. Basically its the same but just remove the ctypes.windll.kernel32 lines as mac and linux won't recognise that

**Comment by geeks121** [comment]
> I also have a mac so will adjust for mac. Basically its the same but just remove the ctypes.windll.kernel32 lines as mac and linux won't recognise that

yeah it just change ctypes with other .. it work in my fork may you add it to update so the script multi platform not only windows.. and it works also in windows without ctypes
