### ISSUE TITLE
Request feature 

### ISSUE THREAD

**Issue by geeks121** [BytePhoenixData/BSCTokenSniper#14]
1. Minimal liquidity balance checker and lock
Its important to check liquidity balance, 
Example 
some token can't sell after buy with 0,25 usd because price impact is too high.

2. Logging for succed swap token only
this log can be used for sell action from profit percentage.
current bot loss their past action after restarted the terminal.
this can be turned on or off.

**Comment by BytePhoenixData** [comment]
Will look into this
