### ISSUE TITLE
Fail during run

### ISSUE THREAD

**Issue by phoenix-blue** [BytePhoenixData/BSCTokenSniper#16]
Hello,

I'm running the script, but after a while I get the next error when it's going to made a swap:

[FAIL] Contract source code isn't verified

What is this for failure and how can I solve this problem?

**Comment by geeks121** [comment]
any log??

**Comment by geeks121** [comment]
do you mean like this?

`[FAIL] Contract source code isn't verified.`

Or 

[FAIL] Contract doesn't use valid PancakeSwap v2 router.

it's normal.. the bot checking for source code ,, and fail meant the contract didn't pass requirement.

**Comment by phoenix-blue** [comment]
Only
 [FAIL] Contract source code isn't verified.

Little bit old school screenshot 😉
![IMG_20210813_134739](https://user-images.githubusercontent.com/13711891/129352954-82b9ca8b-274d-4424-a8cd-9d630ac0e66c.jpg)

**Comment by geeks121** [comment]
it part mini audit.
and it didn't buy the token
and its show the reason printed on screenshot..

**Comment by phoenix-blue** [comment]
Ok, thanks that explains a few things.
Ther small question about the avg. Cpu load, is it normal that it's kind a bit of high? (my case about 70%)

**Comment by geeks121** [comment]
i don't know

python script like this only using some amount not big amount.

it based on where you run the bot script..

example : if you run in pycharm off course it consume more amount.. it define from where you runing it.

i don't care about cpu load btw
