### ISSUE TITLE
AttributeError: 'Eth' object has no attribute 'get_balance'

### ISSUE THREAD

**Issue by SmartShin** [BytePhoenixData/BSCTokenSniper#2]
![image](https://user-images.githubusercontent.com/40012100/124533532-10267e80-de45-11eb-9639-db6875eeec67.png)

This is my issue, any suggestions, thanks!

I got BNB in ​​the Binance Chian wallet

**Comment by Byte-Phoenix** [comment]
What python version are you running? Could also be a problem with web3, are you sure you installed latest version?

**Comment by Byte-Phoenix** [comment]
CnKore-zzb suggested using 'pip install Web3' instead of npm, can u try that and confirm if that works? Thanks

**Comment by littlewe1337** [comment]
> y

yep, before started i'm install web3 with pip, or need delete web3 from npm ?


python 3.9 with latest web3
