### ISSUE TITLE
Closes after a couple mins

### ISSUE THREAD

**Issue by alansheard** [BytePhoenixData/BSCTokenSniper#20]
The window works just fine, then closes after a couple of minutes.

**Comment by BytePhoenixData** [comment]
Sometimes random data can be interpreted from the program that can cause it to crash. In v1.1 I have added a few try and except clauses which should still let the program run if there's an error

**Comment by BytePhoenixData** [comment]
v1.4 should fix that, u can access it in telegram theres a link for bsctokensniper testing
