### ISSUE TITLE
Expanding the mini-audit

### ISSUE THREAD

**Issue by winkelermatthias** [BytePhoenixData/BSCTokenSniper#21]
Hi, getting into many scams still so wondering if we could somehow leverage other project works to check th contract (https://github.com/eth-sri/securify2) . would be cool to have a high end mini audit. thanks for open sourcing your work

**Comment by BytePhoenixData** [comment]
Thanks for using my project, that's an issue I would like to fix at the moment. I will contact bscheck.eu via Twitter and try to see if they can show me their source code
