### ISSUE TITLE
SpecifiedTokenSniper 1.1

### ISSUE THREAD

**Issue by aivarasx987** [BytePhoenixData/BSCTokenSniper#23]
I have a request, could you make so that the bot could buy specific token without checking liquidity?

You just enter token address and it buys the tokens for specified amount of BNB.

Would really appreciate it!

**Comment by Buco11-dev** [comment]
This might be what you're looking for...
https://github.com/CodeWithJoe2020/pythonSniperbot/blob/main/sniper.py

**Comment by Buco11-dev** [comment]
> I have a request, could you make so that the bot could buy specific token without checking liquidity?
> 
> You just enter token address and it buys the tokens for specified amount of BNB.
> 
> Would really appreciate it!

This might be what you're looking for .....
https://github.com/CodeWithJoe2020/pythonSniperbot/blob/main/sniper.py

**Comment by aivarasx987** [comment]
> > I have a request, could you make so that the bot could buy specific token without checking liquidity?
> > You just enter token address and it buys the tokens for specified amount of BNB.
> > Would really appreciate it!
> 
> This might be what you're looking for .....
> https://github.com/CodeWithJoe2020/pythonSniperbot/blob/main/sniper.py

If im not mistaken that one buys only after detecting that a token pair had been created, what im looking for is a bot which could buy an already released token.

**Comment by aivarasx987** [comment]
I have been using wrong private key, im stupid and I should feel bad :D

**Comment by Buco11-dev** [comment]
> > > I have a request, could you make so that the bot could buy specific token without checking liquidity?
> > > You just enter token address and it buys the tokens for specified amount of BNB.
> > > Would really appreciate it!
> > 
> > 
> > This might be what you're looking for .....
> > https://github.com/CodeWithJoe2020/pythonSniperbot/blob/main/sniper.py
> 
> If im not mistaken that one buys only after detecting that a token pair had been created, what im looking for is a bot which could buy an already released token.

In that case, here you go...
https://github.com/CodeWithJoe2020/pancakeswapBot

**Comment by aivarasx987** [comment]
> > > > I have a request, could you make so that the bot could buy specific token without checking liquidity?
> > > > You just enter token address and it buys the tokens for specified amount of BNB.
> > > > Would really appreciate it!
> > > 
> > > 
> > > This might be what you're looking for .....
> > > https://github.com/CodeWithJoe2020/pythonSniperbot/blob/main/sniper.py
> > 
> > 
> > If im not mistaken that one buys only after detecting that a token pair had been created, what im looking for is a bot which could buy an already released token.
> 
> In that case, here you go...
> https://github.com/CodeWithJoe2020/pancakeswapBot

Damn, how did I miss this one...
Already edited original to my needs though, learnt some coding in the process :)
