### ISSUE TITLE
[SUGGESTION] Create a discord so we able to interact with you

### ISSUE THREAD

**Issue by coolerspeex** [BytePhoenixData/BSCTokenSniper#26]

**Comment by Buco11-dev** [comment]
Telegram sounds more convenient to me as not everyone has Discord.

**Comment by BytePhoenixData** [comment]
I'll create a telegram for everyone, whats your telegram username so I can start the group

**Comment by littlewe1337** [comment]
> Я создам телеграмму для всех, какое у вас имя пользователя телеграммы, чтобы я мог начать группу

and me @crytosell_ru

**Comment by BytePhoenixData** [comment]
TELEGRAM GROUP CREATED: https://t.me/joinchat/LivGs7b26iBkNWE0 lets get as many people on here as possible

**Comment by Buco11-dev** [comment]
> I'll create a telegram for everyone, whats your telegram username so I can start the group

Nice 1 mate! Pls add me @Clutch_88

**Comment by coolerspeex** [comment]
Thanks Buddy
