### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by Xspacezero** [BytePhoenixData/BSCTokenSniper#33]
When try to run SpecificTokenSniper v1.3 received below error:-

File "C:\Users\xx\Documents\GitHub\BSCTokenSniper\BSCTokenSniper v1.3\SpecificTokenSniper\bot.py", line 267
    if (tokenAddress = targetContractAddress):
                     ^
SyntaxError: invalid syntax

Updated:-
 if (tokenAddress == targetContractAddress):

Receiving another error after fixing above problem:-

FATAL ERROR: Incorrectly configured config.json file.
Please check that it syntactically correct with no missing/extra colons, quotation marks, curly brackets or omitted entries, or that data types are correct, and restart the program.

Trying to use back SpecificTokenSniper v1.1 config.json but still can't solve the problem.

**Comment by BSC-Contracts** [comment]
Hi thanks for the update I missed the secont = too. then ran in your issue and solved it:

add:
"pancakeSwapFactoryAddress": "0xcA143Ce32Fe78f1f7019d7d551a6402fC5350c73",
"bscNode": "xxx",
"antiBotDelay": "0"

don´t forget. the last line must stop without a comma. then it starts lets see if it runs.
let me know if it works.

**Comment by BytePhoenixData** [comment]
v1.4 fixes that, u can access it in telegram theres a link for bsctokensniper testing
