### ISSUE TITLE
at 1.3 mini audit success

### ISSUE THREAD

**Issue by Justincrdibl** [BytePhoenixData/BSCTokenSniper#34]
[ERROR] buyToken error, please notify dev:
Traceback (most recent call last):
  File "BSCTokenSniper.py", line 353, in Buy
TypeError: can only concatenate str (not "float") to str

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "BSCTokenSniper.py", line 359, in Buy
TypeError: can only concatenate str (not "TypeError") to str

**Comment by Sani0** [comment]
Hey,

Noticed the same problem too
![2](https://user-images.githubusercontent.com/89406110/131499294-da047f54-0694-4777-9f76-c3b08f13ab87.JPG)

**Comment by BytePhoenixData** [comment]
v1.4 fixes that, u can access it in telegram theres a link for bsctokensniper testing
