### ISSUE TITLE
How does the Honeypot detection works and avoid false positive ?

### ISSUE THREAD

**Issue by ValtielChan** [BytePhoenixData/BSCTokenSniper#37]
Hi guys, nice work with this so far, it helped me so much to dev my own tools

BTW I have a question regarding the honeypot detection and false positives. How does the following code makes the contract a Honeypot ? It's looks pretty legit in some contract source code I readed...

`function transferFrom(address sender, address recipient, uint256 amount) public override returns (bool)`

and same for 

`function _approve(address owner, address spender, uint256 amount) internal`

What is "newun" ?

Regards

**Comment by BytePhoenixData** [comment]
v1.4 fixes that and is alot better and reliable at detecting honeypots, u can access it in telegram theres a link for bsctokensniper testing
