### ISSUE TITLE
ERROR execution reverted: TransferHelper: TRANSFER_FROM_FAILED

### ISSUE THREAD

**Issue by Batista00** [BytePhoenixData/BSCTokenSniper#39]
![85d0d1a9dce7c049c8c8e17d7c871dbe](https://user-images.githubusercontent.com/89986339/131855166-a1212747-ca84-4af8-b4f1-73c15cd04d19.png)

The bot should detect if the owner blocks access to liquidity and withdraw the funds or simply not buy, that is, detecting token without owners would be the ideal

**Comment by BytePhoenixData** [comment]
v1.4 uses rugdoc which should be able to filter out most if not all of these scams, please see telegram link to join testing group to get access to v1.4 beta
