### ISSUE TITLE
Issues and Suggestions

### ISSUE THREAD

**Issue by EnorMOZ** [BytePhoenixData/BSCTokenSniper#4]
Great project btw ! Thanks for open sourcing this. 

- This should be OS agnostic. Right now it is windows based.
- After a while it looks like the token parsers just hangs and doesn't pick up new tokens
- Source code verification could have an option to scan again maybe a small delay or retry as sometimes it take a bit for it to show up
- Have an option to watch for a specific contract only vs parsing all new token releases.
- Mini audit check could possibly use a regex system help clean that up and make adding new checks easier.

I am swamped with other projects but when I have time I can help contribute. Great work btw in getting this out to the community !!!

**Comment by dferrandizmont** [comment]
Yep, just tried the script and it freezes randomly at some point :(! Would be amazing if you could add some of that suggestions! 

Anyway, nice work @Byte-Phoenix!

**Comment by Byte-Phoenix** [comment]
Hi, thank you for your suggestions, I'm quite busy at the moment but I'll try installing it on a VM to see if I can replicate the issue.

**Comment by littlewe1337** [comment]
pls fix freezing

**Comment by Byte-Phoenix** [comment]
> pls fix freezing

I haven't experienced freezing myself but I'll look into that

**Comment by Buco11-dev** [comment]
> To make the freezing better use websocket provider instead of a HTTP provider to connect to the BSC network. The best way to be close to first in sniping it to host your own full node

Any resources or references you could point out to achieve this pls?

**Comment by geeks121** [comment]
i fix the freezing.. before the change it freezing till scanned 12 token or 20 token.. now it work well.. just change to websocket using rpc wss ..  

to check the code you can check my github repository

it also runing on linux based system...

its funny linux version also runing in windows version.

**Comment by Buco11-dev** [comment]
> i fix the freezing.. before the change it freezing till scanned 12 token or 20 token.. now it work well.. just change to websocket using rpc wss ..
> 
> to check the code you can check my github repository
> 
> it also runing on linux based system...
> 
> its funny linux version also runing in windows version.

Nice one! I'll check it out. Thanks man

**Comment by geeks121** [comment]
> > i fix the freezing.. before the change it freezing till scanned 12 token or 20 token.. now it work well.. just change to websocket using rpc wss ..
> > to check the code you can check my github repository
> > it also runing on linux based system...
> > its funny linux version also runing in windows version.
> 
> Nice one! I'll check it out. Thanks man

is the bot still freezing?

**Comment by littlewe1337** [comment]
> > > i fix the freezing.. before the change it freezing till scanned 12 token or 20 token.. now it work well.. just change to websocket using rpc wss ..
> > > to check the code you can check my github repository
> > > it also runing on linux based system...
> > > its funny linux version also runing in windows version.
> > 
> > 
> > Nice one! I'll check it out. Thanks man
> 
> is the bot still freezing?

in your fork worked more than 1 day, nice!

**Comment by geeks121** [comment]
> > > > i fix the freezing.. before the change it freezing till scanned 12 token or 20 token.. now it work well.. just change to websocket using rpc wss ..
> > > > to check the code you can check my github repository
> > > > it also runing on linux based system...
> > > > its funny linux version also runing in windows version.
> > > 
> > > 
> > > Nice one! I'll check it out. Thanks man
> > 
> > is the bot still freezing?
> 
> in your fork worked more than 1 day, nice!

how about 1 weeks?

**Comment by littlewe1337** [comment]
> > > > > i fix the freezing.. before the change it freezing till scanned 12 token or 20 token.. now it work well.. just change to websocket using rpc wss ..
> > > > > to check the code you can check my github repository
> > > > > it also runing on linux based system...
> > > > > its funny linux version also runing in windows version.
> > > > 
> > > > 
> > > > Nice one! I'll check it out. Thanks man
> > > 
> > > 
> > > is the bot still freezing?
> > 
> > 
> > in your fork worked more than 1 day, nice!
> 
> how about 1 weeks?

all cool man, waiting for updates and autosales )
