### ISSUE TITLE
V1.3 error and other problems

### ISSUE THREAD

**Issue by Manuu1987** [BytePhoenixData/BSCTokenSniper#42]
Hi,
Thank you for this interesting code. I managed to launch v1.3 through anaconda but now I am getting a bad magic number error even though I am sure I did not before? Do you know a work around for this or should we just wait for the version you will be uploading shortly?
Also with v1.2 and others it seems to run for a bit and just stop - the program is running but no new tokens are sourced? I usually close and reopen if that happens and it starts working against n so maybe I'm being impatient. 
Lastly, the telegram group isn't working. Would be good to chat on there about this.
Thanks

**Comment by BytePhoenixData** [comment]
v1.4 fixes that, also make sure ur python version is latest, u can access it in telegram theres a link for bsctokensniper testing
