### ISSUE TITLE
v1.3 detects coins slower than v1.2

### ISSUE THREAD

**Issue by Bhushansamarth** [BytePhoenixData/BSCTokenSniper#43]
Please check the timeframe in both the screenshots.

v1.3
![v1 3](https://user-images.githubusercontent.com/53603581/131946539-85c78d9e-d630-43c1-943e-90367039c804.PNG)

v1.2
![v1 2](https://user-images.githubusercontent.com/53603581/131946540-33c683a6-7374-4e5a-bd2e-1fa0c278b2cf.PNG)

**Comment by BytePhoenixData** [comment]
Seems odd, v1.3 uses rugdoc.io to check for scams but that shouldn't affect the timeframe that much. Were you using the same server and internet connection? Its probably some sort of delay in the server.
