### ISSUE TITLE
V1.3 Specific Sniper fix

### ISSUE THREAD

**Issue by CryptoCarlos21** [BytePhoenixData/BSCTokenSniper#48]
Update Config to add the missing keys
`{
   "pancakeSwapRouterAddress": "0x10ED43C718714eb63d5aA57B78B54704E256024E",
   "pancakeSwapFactoryAddress": "0xcA143Ce32Fe78f1f7019d7d551a6402fC5350c73",
   "walletAddress": "",
   "walletPrivateKey": "",
   "bscNode": "",
   "amountToSpendPerSnipe": "0.00025",
   "transactionRevertTimeSeconds": "10000",
   "gasAmount": "250000",
   "gasPrice": "5",
   "bscScanAPIKey": "",
   "liquidityPairAddress": "0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c",
   "antiBotDelay": "5",
   "checkSourceCode": "True",
   "checkValidPancakeV2": "True",
   "checkMintFunction": "True",
   "checkHoneypot": "True",
   "checkPancakeV1Router": "True",
   "checkForTest": "True"
}`

update specifiedTokenSniper.py to include the definitions for audit checks that were missing
`    pancakeSwapRouterAddress = configData['pancakeSwapRouterAddress'] #load config data from JSON file into program
    pancakeSwapFactoryAddress = configData['pancakeSwapFactoryAddress']
    walletAddress = configData['walletAddress']
    walletPrivateKey = configData['walletPrivateKey'] #private key is kept safe and only used in the program
    bscNode = configData['bscNode']
    checkValidPancakeV2 = configData['checkValidPancakeV2']
    snipeBNBAmount = float(configData['amountToSpendPerSnipe'])
    transactionRevertTime = int(configData['transactionRevertTimeSeconds']) #number of seconds after transaction processes to cancel it if it hasn't completed
    gasAmount = int(configData['gasAmount'])
    gasPrice = int(configData['gasPrice'])
    bscScanAPIKey = configData['bscScanAPIKey']
    liquidityPairAddress = configData['liquidityPairAddress']
    checkSourceCode = configData['checkSourceCode']
    antiBotDelay = float(configData['antiBotDelay'])`

Fix line 268 to have two == instead of 1 =

`if (tokenAddress == targetContractAddress):`

**Comment by BytePhoenixData** [comment]
v1.4 fixes that, u can access it in telegram theres a link for bsctokensniper testing
