### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by mkamdoum** [BytePhoenixData/BSCTokenSniper#49]
Anyone getting this error when trying to run `python3 BSCTokenSniper.py` on Mac?

BSCTokenSniper/BSCTokenSniper.py", line 40, in <module>
    ctypes.windll.kernel32.SetConsoleTitleW("BSCTokenSniper | Loading...")
AttributeError: module 'ctypes' has no attribute 'windll'

**Comment by defifarms** [comment]
I got this error too

**Comment by mkamdoum** [comment]
> I got this error too

Please Remove all "Ctypes" Instance? Replace with "Print"

**Comment by BytePhoenixData** [comment]
v1.4 has fixed that, please see telegram link to join testing group to get access to v1.4 beta
