### ISSUE TITLE
no module web3 found

### ISSUE THREAD

**Issue by adigunn** [BytePhoenixData/BSCTokenSniper#5]
i have installed web3 with npm and pip but its say no module web3 found, how to fix it

**Comment by Smiteshraghi** [comment]
i have installed web3 with npm and pip but its say no module web3 found, how to fix it

**Comment by BytePhoenixData** [comment]
I have just installed python on my laptop (windows 8) and got it successfully to work. I installed python 3.9.6 and installed web3 using 'npm install web3' but that didn't work.

Fix that worked for me:
Try 'py -m pip install web3' or replace 'py' with python if you have a python older version. 

Worked right away after that. Let me know if that works.
