### ISSUE TITLE
Great but can you optimize for reduce CPU Usage

### ISSUE THREAD

**Issue by suneth2** [BytePhoenixData/BSCTokenSniper#51]
I'm using i5 8th gen lap my CPU usage goes for 40% when running this, is there anyway to reduce it becoz, i have to do other works while running this without heating the laptop,
Thank You

**Comment by BytePhoenixData** [comment]
v1.4 should be better with CPU usage, please bear with us it wont be long till its released

**Comment by BytePhoenixData** [comment]
v1.4 beta is available for testing, see the telegram
