### ISSUE TITLE
None

### ISSUE THREAD

**Issue by tuttowp** [BytePhoenixData/BSCTokenSniper#52]
(redacted)

**Comment by suneth2** [comment]
I don't think so. this have clear source codes for every versions

**Comment by meanstackofdoom** [comment]
> They stole 0.1bnb from the wallet I made only to use their bot.
> 
> Be careful code is obfuscated so they can steal you private key.
> 
> DO NOT INSERT YOUR PRIVATE KEY. BE ADVISED

umm no.

**Comment by BytePhoenixData** [comment]
Scammer trying to make false accusations

**Comment by tuttowp** [comment]
You are the scammer and you deleted so people won't see
