### ISSUE TITLE
SpecifiedTokenSniper

### ISSUE THREAD

**Issue by iwashim** [BytePhoenixData/BSCTokenSniper#54]
Hey there, I get an error when running the above .py
\specifiedTokenSniper.py", line 267
    if (tokenAddress = targetContractAddress):

-----------------------------
I then edit the code to a double ==
and run it again but then I get that the json file is not configured correctly(Even though I double checked everything)

**Comment by BytePhoenixData** [comment]
SpecificTokenSniper is improved alot with v1.4, but that isn't ready yet. Can u post your config file without the private key / other details?

**Comment by iwashim** [comment]
> SpecificTokenSniper is improved alot with v1.4, but that isn't ready yet. Can u post your config file without the private key / other details?

It is just the normal file but sure,

{
   "walletAddress": "snip",
   "walletPrivateKey": "snip",
   "pancakeSwapRouterAddress": "0x10ED43C718714eb63d5aA57B78B54704E256024E",
   "amountToSpendPerSnipe": "0.00025",
   "transactionRevertTimeSeconds": "10000",
   "gasAmount": "300000",
   "gasPrice": "5",
   "bscScanAPIKey": "snip",
   "liquidityPairAddress": "0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c"
}

**Comment by liquidpeachy** [comment]
> > SpecificTokenSniper is improved alot with v1.4, but that isn't ready yet. Can u post your config file without the private key / other details?
> 
> It is just the normal file but sure,
> 
> { "walletAddress": "snip", "walletPrivateKey": "snip", "pancakeSwapRouterAddress": "0x10ED43C718714eb63d5aA57B78B54704E256024E", "amountToSpendPerSnipe": "0.00025", "transactionRevertTimeSeconds": "10000", "gasAmount": "300000", "gasPrice": "5", "bscScanAPIKey": "snip", "liquidityPairAddress": "0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c" }
> 
> There is a guy a few days ago that posted a fix for the issue but he is implementing code I'm not confident tampering with.

I'm getting this issue too. Did you manage to fix it?
