### ISSUE TITLE
Fixed last issue with changing  a setting from 7 to 0, but i do notice the bot "freezes" until i press enter

### ISSUE THREAD

**Issue by jahanshahub** [BytePhoenixData/BSCTokenSniper#56]
Is there any way to fix that? The bot will trade seemingly fine, albeit not showing a profit as of yet, however after some time of inactivity I go ahead and press enter and floods errors. 
Cytools and Functools are mentioned. 

attached a screenshot of what i could grab but it goes on for a while. 
![image](https://user-images.githubusercontent.com/12451352/133128711-1db62e32-51a3-434d-afd5-8a1e99e14361.png)

**Comment by BytePhoenixData** [comment]
v1.4 beta is available for testing and should fix this issue along with alot more. https://t.me/joinchat/hRBgcgHwxxY1NTA0

**Comment by jahanshahub** [comment]
the invite link doesnt work for me!
