### ISSUE TITLE
feature : anti rug and can't sell

### ISSUE THREAD

**Issue by geeks121** [BytePhoenixData/BSCTokenSniper#6]
Anti rug scan and can't sell tester.

buy with small amount and try sell the token, if token succesfully sell,, then buy with big amount of bnb / busd

**Comment by BytePhoenixData** [comment]
Seems a bit unnecessary, if I can get the honeypot detection code to work better then this isn't really needed.

**Comment by Buco11-dev** [comment]
That would be great! How do we know when you've released an update?

**Comment by geeks121** [comment]
in my side opinion.. this workflow can be option enable and disable... i know someone who are sniper and become rich.. his method is to check the token. if sell succesfully,, then he buy more ,,, and if can't sell the bot refused to buy more and skip.. event the contract look like legit..

or add it to scan contract only if the bot find can't sell code ,, than refused to buy
