### ISSUE TITLE
[Question] Why isn't the source code provided?

### ISSUE THREAD

**Issue by evris99** [BytePhoenixData/BSCTokenSniper#67]
The only files I found were .pyc files which can be decompiled with tools like [decompyle3](https://github.com/rocky/python-decompile3) but it is a hassle.

**Comment by Tulle121** [comment]
decompilation is poor in python 3.9 and there has been added obfuscation. This is not meant to be open source code. It does indeed seem dangerous to run a binary and paste you keys, so do it in isolation with a small key and join our telegram community for others to vouch.
