### ISSUE TITLE
Honeypot code needs updating

### ISSUE THREAD

**Issue by Gcvanasel** [BytePhoenixData/BSCTokenSniper#9]
Take a recently added contract as an example: 0xe4B473c657120ebc91586c335ad9E5aF203F2dC3
Look at the transfer and approve functions. 

I see more complex code poping up to bypass honeypot identification bots. 

Let me know if you would like to collab in finding a way to be optimal in finding the 1% of tokens that are not scams

**Comment by Gcvanasel** [comment]
I think the only way to prevent hard rugs are to front run their transactions and to do that you need to run your own node. I don't ape in unless there is a minimum of 10BNB liquidity. Then monitor the transactions and as soon as liquidity is being removed up the gas limit and price and attempt to front run the rug.

Drop me a line on Telegram: CvA_CryptoPlayground

My time zone is GMT+2

**Comment by BytePhoenixData** [comment]
Nice mate thank you, will dm you tomorrow

**Comment by Gcvanasel** [comment]
Enhancement not an issue
